
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: jvssvarma
  password: Sunny9999

development:
  <<: *default
  database: recipe-box_development

test:
  <<: *default
  database: recipe-box_test

production:
  <<: *default
  database: recipe-box_production
  username: recipe-box
  password: <%= ENV['recipe-box_DATABASE_PASSWORD'] %>
