# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 073f8369c9184cfd01f539b7c656069e51113d385ba733303c0e7b02aa120bba808de446e42b285c36a713e8a762c3c83ab92b473a272bd6b517b6e517e4f2b3

test:
  secret_key_base: 083a97b63508d1fd1c7930110419d40bcc38e26219118ae2c356d5268a0ff2b8f9e4170e6223172d3e443b14bf07285b453e99f48fb32e908b95325dba86547b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
